### ISSUE TITLE
Run an optimization with only the  cameras to make sure we did nothing wrong in last Tuesday's changes.

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/AtlasCarCalibration#45]
@afonsocastro , can you do this?

**Comment by afonsocastro** [comment]
yes, i can

**Comment by afonsocastro** [comment]
yes, i can

**Comment by afonsocastro** [comment]
It is all working just fine. 
Here are the results obtained for the optimization with only cameras vs calib camera:
![Captura de ecrã de 2019-11-09 18-31-29](https://user-images.githubusercontent.com/47828797/68533359-91033f00-031f-11ea-98ef-01bfb31f6d07.png)


AVERAGE ERROR (our optimization):
x = 2.20814818259 pix ;   y = 0.732894332321 pix

AVERAGE ERROR (openCV stereo calibration):
x = 285.961612654 pix ;   y = 15.976624504 pix

AVERAGE ERROR (openCV calibrate camera):
x = 6.93868496473 pix ;   y = 6.00126505319 pix

I noticed that the first guess xacro file must already exist since the program will only rewrite it. Because of this, the first calibration ever will not work if the user does not create the xacro before.

README updated with the new command lines.

**Comment by miguelriemoliveira** [comment]
The values for the stereo calibration do not make sense ... do you know what is the problem?

**Comment by afonsocastro** [comment]
After finding and solving the problem of the stereo calibration implementation, here are the obtained results:

![Captura de ecrã de 2019-11-12 12-03-24](https://user-images.githubusercontent.com/47828797/68670391-bfae2f00-0544-11ea-8e61-73f55b2bad9c.png)

AVERAGE ERROR (our optimization):
x = 2.20814818259 pix ;   y = 0.732894332321 pix

AVERAGE ERROR (openCV stereo calibration):
x = 1.87823367918 pix ;   y = 0.841562853078 pix

AVERAGE ERROR (openCV calibrate camera):
x = 2.60907725178 pix ;   y = 3.77128716793 pix

They are closest to what it is expected, but are these values good enough?

**Comment by eupedrosa** [comment]
What was the error? You should also provide the error deviation to better judge the data. Just the mean error is not enough.

**Comment by miguelriemoliveira** [comment]
Hi, yes std would be interesting, but we also get a feeling of the data deviation from the graphic. 
Nonetheless, If you can add the info that would be another plus ...

**Comment by miguelriemoliveira** [comment]
Also, I would close this issue since the title seems to have been completely fulfilled...

**Comment by afonsocastro** [comment]
std info is already added.
I will commit and close this issue soon
